# Generated by Django 6.0 on 2025-12-10 16:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_roleupgraderequest_kyc_document_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='KycAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('kyc_verified', 'KYC Verified'), ('kyc_rejected', 'KYC Rejected'), ('role_approved', 'Role Approved'), ('role_rejected', 'Role Rejected')], max_length=50)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='accounts.roleupgraderequest')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
