# Generated by Django 5.2.7 on 2025-10-25 14:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtistProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage_name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('bio', models.TextField()),
                ('genre', models.CharField(help_text='Music genre (e.g., Afrobeats, Hip-hop, R&B)', max_length=100)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='artist_profiles/')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='artist_covers/')),
                ('instagram_handle', models.CharField(blank=True, max_length=50)),
                ('twitter_handle', models.CharField(blank=True, max_length=50)),
                ('tiktok_handle', models.CharField(blank=True, max_length=50)),
                ('youtube_channel', models.URLField(blank=True)),
                ('spotify_link', models.URLField(blank=True)),
                ('apple_music_link', models.URLField(blank=True)),
                ('booking_email', models.EmailField(blank=True, max_length=254)),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('is_verified', models.BooleanField(default=False)),
                ('is_featured', models.BooleanField(default=False)),
                ('follower_count', models.PositiveIntegerField(default=0)),
                ('reel_count', models.PositiveIntegerField(default=0)),
                ('total_views', models.PositiveIntegerField(default=0)),
                ('total_likes', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='artist_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Reel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('description', models.TextField(blank=True)),
                ('content_type', models.CharField(choices=[('video', 'Video'), ('image', 'Image')], default='video', max_length=10)),
                ('video_file', models.FileField(blank=True, null=True, upload_to='reels/videos/')),
                ('image_file', models.ImageField(blank=True, null=True, upload_to='reels/images/')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='reels/thumbnails/')),
                ('duration', models.PositiveIntegerField(default=0, help_text='Duration in seconds')),
                ('allow_comments', models.BooleanField(default=True)),
                ('allow_downloads', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('is_featured', models.BooleanField(default=False)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('like_count', models.PositiveIntegerField(default=0)),
                ('share_count', models.PositiveIntegerField(default=0)),
                ('download_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reels', to='artists.artistprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followers', to='artists.artistprofile')),
                ('follower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following_artists', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['artist', 'created_at'], name='artists_fol_artist__4a1dfe_idx'), models.Index(fields=['follower', 'created_at'], name='artists_fol_followe_035bc1_idx')],
                'unique_together': {('artist', 'follower')},
            },
        ),
        migrations.CreateModel(
            name='ReelLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='artists.reel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liked_reels', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('reel', 'user')},
            },
        ),
        migrations.CreateModel(
            name='ReelView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField(blank=True)),
                ('viewed_at', models.DateTimeField(auto_now_add=True)),
                ('reel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='artists.reel')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='viewed_reels', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['reel', 'viewed_at'], name='artists_ree_reel_id_aac915_idx')],
            },
        ),
    ]
